### ISSUE TITLE
No readme present

### ISSUE THREAD

**Issue by Veerhan-glitch** [Veerhan-glitch/YouTube_Audio_Downloader#1]
Create a valid and quality readme.md file for this repo.

**Comment by parth-verma7** [comment]
Hey @Veerhan-glitch  I would like to work upon this issue, can u please assign it to me?

**Comment by Veerhan-glitch** [comment]
Yea sure.
Good luck.

**Comment by Veerhan-glitch** [comment]
@parth-verma7 pls creat a pr so that I can accept ur contribution
