### ISSUE TITLE
Save files to an user specified folder instead of the same folder as of the code

### ISSUE THREAD

**Issue by 1-Rishabh-Jain-1** [Veerhan-glitch/YouTube_Audio_Downloader#5]
Take the path input from the user where they want to save the file and download the file at that destination. If the user inputs an invaid path, print an error message displaying the same.

**Comment by Veerhan-glitch** [comment]
alright i am assign it to you.
you have 5 days time for this issue (as this was first raised by another user (zyetta)) if that's alright

**Comment by Veerhan-glitch** [comment]
have you completed it?

**Comment by 1-Rishabh-Jain-1** [comment]
yes i completed it

**Comment by Veerhan-glitch** [comment]
oh yea right i forgot i accepted ur pr thanks and sorry for the confusion.
